#!/bin/bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

clear
echo
echo "#############################################################"
echo "# Shadowsocks Python Manyuser For Debian/Ubuntu/Centos      #"
echo "# Author: JulySnow <603723963@qq.com>                       #"
echo "# Thanks: @zd423 <zdfans.com> @glzhaojin <zhaoj.in>         #"
echo "#############################################################"
echo

arg1=$1

Get_Dist_Name()
{
    if grep -Eqi "CentOS" /etc/issue || grep -Eq "CentOS" /etc/*-release; then
        DISTRO='CentOS'
        PM='yum'
    elif grep -Eqi "Debian" /etc/issue || grep -Eq "Debian" /etc/*-release; then
        DISTRO='Debian'
        PM='apt'
    elif grep -Eqi "Ubuntu" /etc/issue || grep -Eq "Ubuntu" /etc/*-release; then
        DISTRO='Ubuntu'
        PM='apt'		
	else
        DISTRO='unknow'
    fi
}

Get_Dist_Name

start_shadowsocks()
{
if [ "$DISTRO" == "CentOS" ]; then
	# CentOS
	/etc/init.d/supervisord stop
	fi
	if [[ "$DISTRO" == "Ubuntu" ]] || [[ "$DISTRO" == "Debian" ]]; then
	# Debian/Ubuntu
	supervisorctl reload
	supervisorctl start all
	fi
}

stop_shadowsocks()
{
	if [ "$DISTRO" == "CentOS" ]; then
	# CentOS
	/etc/init.d/supervisord start
	fi
	if [[ "$DISTRO" == "Ubuntu" ]] || [[ "$DISTRO" == "Debian" ]]; then
	# Debian/Ubuntu
	supervisorctl reload
	supervisorctl stop all
	fi
}

restart_shadowsocks()
{
	if [ "$DISTRO" == "CentOS" ]; then
	# CentOS
	/etc/init.d/supervisord restart
	fi
	if [[ "$DISTRO" == "Ubuntu" ]] || [[ "$DISTRO" == "Debian" ]]; then
	# Debian/Ubuntu
	supervisorctl reload
	supervisorctl restart all
	fi
}

showlog__shadowsocks()
{
	if [ "$DISTRO" == "CentOS" ]; then
	# CentOS
	echo "暂且不支持,欢迎联系飞雪!"
	fi
	if [[ "$DISTRO" == "Ubuntu" ]] || [[ "$DISTRO" == "Debian" ]]; then
	# Debian/Ubuntu
	supervisorctl tail -f shadowsocks stderr
	fi
}

updata__shadowsocks()
{
echo "Download Shadowsocks Updata Pack And Apply..."
cd /root/shadowsocks
git pull
echo "Updata Completed!"
}

case "${arg1}" in
    start)
        start_shadowsocks
        ;;
    stop)
        stop_shadowsocks
        ;;
    restart)
        restart_shadowsocks
        ;;
    showlog)
        showlog__shadowsocks
        ;;
    updata)
        updata__shadowsocks
        ;;
    *)
        echo "Usage: shadowsocks {start|stop|showlog|restart}"
esac
exit